# Generated by Django 5.2.4 on 2025-07-08 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=15)),
                ('teacher_date_of_birth', models.DateField()),
                ('teacher_mobile', models.CharField(max_length=15)),
                ('teacher_joining_date', models.DateField()),
                ('teacher_qualification', models.CharField(max_length=50)),
                ('teacher_experience', models.CharField(max_length=100)),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('teacher_address', models.TextField()),
                ('teacher_city', models.CharField(max_length=100)),
                ('teacher_state', models.CharField(max_length=100)),
                ('teacher_zip_code', models.CharField(max_length=20)),
                ('teacher_country', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
