# Generated by Django 5.2.4 on 2025-07-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_class',
            field=models.CharField(default='9', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_section',
            field=models.CharField(default='A', max_length=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_subject',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
