# Generated by Django 5.2.4 on 2025-07-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_teacher_teacher_class_teacher_teacher_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_class',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_section',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_subject',
            field=models.CharField(max_length=50),
        ),
    ]
