# Generated by Django 5.2.4 on 2025-07-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_alter_teacher_teacher_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_section',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_subject',
        ),
    ]
