# Generated by Django 5.2.4 on 2025-07-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('head_of_department', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('number_of_students', models.PositiveIntegerField()),
            ],
        ),
    ]
