# Generated by Django 5.2.4 on 2025-07-21 20:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head_of_department',
        ),
        migrations.RemoveField(
            model_name='department',
            name='number_of_students',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_class',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_teacher': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_led', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.CharField(default='9', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default='OOP', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
