# Generated by Django 5.2.4 on 2025-07-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ld89cixinVTS8GITWzNa3b2kZDoGLSoB', editable=False, max_length=32, unique=True),
        ),
    ]
