# Generated by Django 5.2.4 on 2025-07-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='EH6L2o8pn2YBQtY0D6oFAk5ry1WZQtKi', editable=False, max_length=32, unique=True),
        ),
    ]
